### ISSUE TITLE
pip로 설치시에 pandas, requests 등과 같은 모듈을 설치하는 과정이 필요합니다.

### ISSUE THREAD

**Issue by jeongmincha** [sharebook-kr/pykorbit#3]
해당 모듈에서 필요로 하는 pandas, request와 같은 기본 모듈들도
이 라이브러리를 설치할 때 같이 설치하도록 셋업을 해주셔야 할거 같습니다.
Python 3.8.8 어떠한것도 설치하지 않은 버전에서
```
$ pip install pykorbit
```
한 후에도 pandas, requests 등이 깔려 있지 않아서 추가로 pip install 해야 하는 일이 발생했었습니다.

**Comment by mr-yoo** [comment]
1년 째 미루고 있다가 이제야 수정하네요..
`pandas`, `requests`, `PyJWT` 자동 설치되도록 수정했습니다. 

reporting 감사합니다!
