### ISSUE TITLE
인증방식 변경과 get_ohlc 함수에서 MED 통화 조회 문제

### ISSUE THREAD

**Issue by sigmafelix** [sharebook-kr/pykorbit#4]
안녕하세요, 패키지를 만들어 주신 덕분에 편리하게 Python에서 Korbit API를 이용하고 있습니다.

Korbit API Docs를 보니 password 방식이 2021년 5월 3일 부로 지원되지 않는다고 합니다.
`pykorbit.Korbit()` 함수의 방식도 그에 맞게 변경되어야 할 필요가 있어 보입니다. 함수 내부적으로는 ID와 PW 없이도 token을 발급하도록 설정되어 있는 듯한데, 앞으로는 ID와 PW를 요구하지 않도록 하는 것이 적절하지 않을까 생각됩니다.

한편, `get_ohlc()` 함수에서 MED 통화를 조회할 때 통화 이름을 MEDIB로 해야만 내역이 정상적으로 조회되는데 (아마 참조 사이트의 고유 통화 코드가 MEDIB인 듯 합니다) 이 부분도 패치에서 인수는 MED로 받되 내부 URL 호출 시에는 MEDIB가 되도록 수정되어야 할 것 같습니다.

감사합니다.

**Comment by mr-yoo** [comment]
인증 방식 변경에 따라 `ID` 및 `PW`를 수정했습니다.
- https://github.com/sharebook-kr/pykorbit/commit/40b28cf5268aca6f318a5898baf9413785a0a7de

`get_ohlcv` 함수 또한 동작하도록 수정했습니다. 
- https://github.com/sharebook-kr/pykorbit/commit/97e4669058afcb89036e76a10534b4ea63e41a27

상세한 리포팅 정말 감사합니다.

**Comment by sigmafelix** [comment]
반영해 주셔서 감사합니다. 이슈가 해결되었기 때문에 제가 닫도록 하겠습니다.
